[general]
import = [
  "~/.config/alacritty/themes/dracula/dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10}

# decorations = "None"
decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"
size = 14

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
